INSERT INTO DEV_TRF_DB.IAUDITOR_TRF.IAUDITOR_ACTION_ASSIGNEES (
    ID,
    ACTION_ID,
    ASSIGNEE_ID,
    TYPE,
    NAME,
    ORGANISATION_ID,
    MODIFIED_AT,
    EXPORTED_AT
)
SELECT
    LEFT(DATA.value:id::string, 64) AS ID,
    DATA.value:action_id::string AS ACTION_ID,
    DATA.value:assignee_id::string AS ASSIGNEE_ID,
    DATA.value:type::string AS TYPE,
    DATA.value:name::string AS NAME,
    DATA.value:organisation_id::string AS ORGANISATION_ID,
    TO_CHAR(TO_TIMESTAMP_TZ(DATA.value:modified_at::string), 'YYYY-MM-DD') AS MODIFIED_AT,
    TO_CHAR(TO_TIMESTAMP_TZ(DATA_DATE), 'YYYY-MM-DD') AS EXPORTED_AT
FROM
    DEV_RAW_DB.IAUDITOR_RAW.IAUDITOR_ACTION_ASSIGNEES,
    LATERAL FLATTEN(input => JSON_PAYLOAD:data) AS DATA;

