INSERT INTO DEV_TRF_DB.IAUDITOR_TRF.IAUDITOR_SITE_MEMBERS (
    SITE_ID,
    MEMBER_ID,
    EXPORTED_AT
)
SELECT
    DATA.value:site_id::string AS SITE_ID,
    DATA.value:member_id::string AS MEMBER_ID,
    TO_CHAR(TO_TIMESTAMP_TZ(DATA_DATE), 'YYYY-MM-DD') AS EXPORTED_AT
FROM
    DEV_RAW_DB.IAUDITOR_RAW.IAUDITOR_SITE_MEMBERS,
    LATERAL FLATTEN(input => JSON_PAYLOAD:data) AS DATA;
