import datetime
import polars as pl
import os

from polars import Datetime
current_time = str(datetime.datetime.now())

# Current directory
current_dir = os.path.dirname(__file__)
snowflake_config = os.path.join(current_dir, '../../code/include/config.ini')

exporter_config = 'iAuditor-Exporter-config.ini'


table_prefix = "IAUDITOR_"

urls = {
    "actions": "https://api.safetyculture.io/feed/actions",
    "action_assignees": "https://api.safetyculture.io/feed/action_assignees",
    "action_timeline_items": "https://api.safetyculture.io/feed/action_timeline_items",
    "groups": "https://api.safetyculture.io/feed/groups",
    "group_users": "https://api.safetyculture.io/feed/group_users",
    "inspections": "https://api.safetyculture.io/feed/inspections",
    "inspection_items": "https://api.safetyculture.io/feed/inspection_items",
    "schedules": "https://api.safetyculture.io/feed/schedules",
    "schedule_assignees": "https://api.safetyculture.io/feed/schedule_assignees",
    "sites": "https://api.safetyculture.io/feed/sites",
    "site_members": "https://api.safetyculture.io/feed/site_members",
    "templates": "https://api.safetyculture.io/feed/templates",
    "template_permissions": "https://api.safetyculture.io/feed/template_permissions",
    "users": "https://api.safetyculture.io/feed/users",
}

json_keys = {
    "actions": {
        "action_id": "id",
        "title": "title",
        "description": "description",
        "site_id": "site_id",
        "priority": "priority",
        "status": "status",
        "due_date": "due_date",
        "created_at": "created_at",
        "modified_at": "modified_at",
        "creator_user_id": "creator_user_id",
        "assignee_user_name": "assignee_user_name",
        "template_id": "template_id",
        "audit_id": "audit_id",
        "audit_title": "audit_title",
        "audit_item_id": "audit_item_id",
        "audit_item_label": "audit_item_label",
        "organisation_id": "organisation_id",
        "completed_at": "completed_at",
        "action_label": "action_label",
        "deleted": "deleted",
        "asset_id": "asset_id",
    },
    "action_assignees": {
        "id": "id",
        "action_id": "action_id",
        "assignee_id": "assignee_id",
        "type": "type",
        "creator_user_name": "creator_user_name",
        "organisation_id": "organisation_id",
        "modified_at": "modified_at",
    },
    "action_timeline_items": {
        "item_id": "item_id",
        "task_id": "task_id",
        "organisation_id": "organisation_id",
        "task_creator_name": "task_creator_name",
        "timestamp": "timestamp",
        "creator_id": "creator_id",
        "creator_name": "creator_name",
        "item_type": "item_type",
        "item_data": "item_data",
    },
    "groups": {
        "group_id": "group_id",
        "organisation_id": "organisation_id",
        "name": "name",
    },
    "group_users": {
        "user_id": "user_id",
        "group_id": "group_id",
        "organisation_id": "organisation_id",
    },
    "inspections": {
        "audit_id": "audit_id",
        "name": "name",
        "archived": "archived",
        "owner_name": "owner_name",
        "owner_id": "owner_id",
        "author_name": "author_name",
        "author_id": "author_id",
        "score": "score",
        "max_score": "max_score",
        "score_percentage": "score_percentage",
        "duration": "duration",
        "organisation_id": "organisation_id",
        "template_name": "template_name",
        "template_author": "template_author",
        "site_id": "site_id",
        "date_started": "date_started",
        "date_completed": "date_completed",
        "date_modified": "date_modified",
        "created_at": "created_at",
        "modified_at": "modified_at",
        "document_no": "document_no",
        "prepared_by": "prepared_by",
        "location": "location",
        "conducted_on": "conducted_on",
        "personnel": "personnel",
        "client_site": "client_site",
        "latitude": "latitude",
        "longitude": "longitude",
        "web_report_link": "web_report_link",
        "deleted": "deleted",
        "asset_id": "asset_id",
    },
    "inspection_items": {
        "id": "id",
        "item_id": "item_id",
        "audit_id": "audit_id",
        "item_index": "item_index",
        "template_id": "template_id",
        "parent_id": "parent_id",
        "created_at": "created_at",
        "modified_at": "modified_at",
        "type": "type",
        "category": "category",
        "category_id": "category_id",
        "organisation_id": "organisation_id",
        "parent_ids": "parent_ids",
        "label": "label",
        "response": "response",
        "response_id": "response_id",
        "response_set_id": "response_set_id",
        "is_failed_response": "is_failed_response",
        "comment": "comment",
        "media_files": "media_files",
        "media_ids": "media_ids",
        "media_hypertext-references": "media_hypertext-reference",
        "score": "score",
        "max_score": "max_score",
        "score_percentage": "score_percentage",
        "combined_score": "combined_score",
        "combined_max_score": "combined_max_score",
        "combined_score_percentage": "combined_score_percentage",
        "mandatory": "mandatory",
        "inactive": "inactive",
        "location_latitude": "location_latitude",
        "location_longitude": "location_longitude",
    },
    "schedules": {
        "schedule_id": "id",
        "description": "description",
        "recurrence": "recurrence",
        "duration": "duration",
        "modified_at": "modified_at",
        "from_date": "from_date",
        "to_date": "to_date",
        "start_time_hour": "start_time_hour",
        "start_time_minute": "start_time_minute",
        "all_must_complete": "all_must_complete",
        "status": "status",
        "organisation_id": "organisation_id",
        "timezone": "timezone",
        "can_late_submit": "can_late_submit",
        "site_id": "site_id",
        "template_id": "template_id",
        "creator_user_id": "creator_user_id",
    },
    "schedule_assignees": {
        "id": "id",
        "schedule_id": "schedule_id",
        "assignee_id": "assignee_id",
        "organisation_id": "organisation_id",
        "type": "type",
        "name": "name",
    },
    "sites": {
        "site_id": "site_id",
        "name": "name",
        "creator_id": "creator_id",
        "organisation_id": "organisation_id",
        "deleted": "deleted",
        "site_uuid": "site_uuid",
        "meta_label": "meta_label",
        "parent_id": "parent_id",
    },
    "site_members": {
        "site_id": "site_id",
        "member_id": "member_id",
    },
    "templates": {
        "template_id": "template_id",
        "archived": "archived",
        "name": "name",
        "description": "description",
        "organisation_id": "organisation_id",
        "owner_name": "owner_name",
        "owner_id": "owner_id",
        "author_name": "author_name",
        "author_id": "author_id",
        "created_at": "created_at",
        "modified_at": "modified_at",
    },
    "template_permissions": {
        "permission_id": "id",
        "template_id": "template_id",
        "permission": "permission",
        "assignee_id": "assignee_id",
        "assignee_type": "assignee_type",
        "organisation_id": "organisation_id",
    },
    "users": {
        "user_id": "user_id",
        "organisation_id": "organisation_id",
        "email": "email",
        "first_name": "firstname",
        "last_name": "lastname",
        "active": "active",
        "last_seen_at": "last_seen_at",
    },
}

add_exported_at = [ "action_assignees", "groups", "group_users", "inspections", "inspection_items", "schedules",
                        "schedule_assignees", "sites", "site_members", "templates", "users" ]

datatypes = {
    "users": {
        'user_id': pl.Utf8,
        'organisation_id': pl.Utf8,
        'email': pl.Utf8,
        'firstname': pl.Utf8,
        'lastname': pl.Utf8,
        'active': pl.Utf8,
        'last_seen_at': pl.Utf8,
        'exported_at': pl.Utf8,
    },
    "templates": {
        'template_id': pl.Utf8,
        'archived': pl.Utf8,
        'name': pl.Utf8,
        'description': pl.Utf8,
        'organisation_id': pl.Utf8,
        'owner_name': pl.Utf8,
        'owner_id': pl.Utf8,
        'author_name': pl.Utf8,
        'author_id': pl.Utf8,
        'created_at': pl.Utf8,
        'modified_at': pl.Utf8,
        'exported_at': pl.Utf8,
    },
    "template_permissions": {
        'permission_id': pl.Utf8,
        'template_id': pl.Utf8,
        'permission': pl.Utf8,
        'assignee_id': pl.Utf8,
        'assignee_type': pl.Utf8,
        'organisation_id': pl.Utf8,
    },
    "sites": {
        'site_id': pl.Utf8,
        'name': pl.Utf8,
        'creator_id': pl.Utf8,
        'organisation_id': pl.Utf8,
        'exported_at': pl.Utf8,
        'deleted': pl.Utf8,
        'site_uuid': pl.Utf8,
        'meta_label': pl.Utf8,
        'parent_id': pl.Utf8,
    },
    "schedules": {
        'schedule_id': pl.Utf8,
        'description': pl.Utf8,
        'recurrence': pl.Utf8,
        'duration': pl.Utf8,
        'modified_at': pl.Utf8,
        'exported_at': pl.Utf8,
        'from_date': pl.Utf8,
        'to_date': pl.Utf8,
        'start_time_hour': pl.Int32,
        'start_time_minute': pl.Int32,
        'all_must_complete': pl.Utf8,
        'status': pl.Utf8,
        'organisation_id': pl.Utf8,
        'timezone': pl.Utf8,
        'can_late_submit': pl.Utf8,
        'site_id': pl.Utf8,
        'template_id': pl.Utf8,
        'creator_user_id': pl.Utf8,
    },
    "schedule_assignees": {
        'id': pl.Utf8,
        'schedule_id': pl.Utf8,
        'assignee_id': pl.Utf8,
        'organisation_id': pl.Utf8,
        'type': pl.Utf8,
        'name': pl.Utf8,
        'exported_at': pl.Utf8,
    },
    "inspections": {
        'audit_id': pl.Utf8,
        'name': pl.Utf8,
        'archived': pl.Utf8,
        'owner_name': pl.Utf8,
        'owner_id': pl.Utf8,
        'author_name': pl.Utf8,
        'author_id': pl.Utf8,
        'score': pl.Float64,
        'max_score': pl.Float64,
        'score_percentage': pl.Float64,
        'duration': pl.Int64,
        'template_id': pl.Utf8,
        'organisation_id': pl.Utf8,
        'template_name': pl.Utf8,
        'template_author': pl.Utf8,
        'site_id': pl.Utf8,
        'date_started': pl.Utf8,
        'date_completed': pl.Utf8,
        'date_modified': pl.Utf8,
        'created_at': pl.Utf8,
        'modified_at': pl.Utf8,
        'exported_at': pl.Utf8,
        'document_no': pl.Utf8,
        'prepared_by': pl.Utf8,
        'location': pl.Utf8,
        'conducted_on': pl.Utf8,
        'personnel': pl.Utf8,
        'client_site': pl.Utf8,
        'latitude': pl.Utf8,
        'longitude': pl.Utf8,
        'web_report_link': pl.Utf8,
        'deleted': pl.Utf8,
        'asset_id': pl.Utf8,
    },
    "groups": {
        'group_id': pl.Utf8,
        'name': pl.Utf8,
        'organisation_id': pl.Utf8,
        'exported_at': pl.Utf8,
    },
    "group_users": {
        'user_id': pl.Utf8,
        'group_id': pl.Utf8,
        'organisation_id': pl.Utf8,
        'exported_at': pl.Utf8,
    },
    "actions": {
        'action_id': pl.Utf8,
        'title': pl.Utf8,
        'description': pl.Utf8,
        'site_id': pl.Utf8,
        'priority': pl.Utf8,
        'status': pl.Utf8,
        'due_date': pl.Utf8,
        'created_at': pl.Utf8,
        'modified_at': pl.Utf8,
        'exported_at': pl.Utf8,
        'creator_user_id': pl.Utf8,
        'creator_user_name': pl.Utf8,
        'template_id': pl.Utf8,
        'audit_id': pl.Utf8,
        'audit_title': pl.Utf8,
        'audit_item_id': pl.Utf8,
        'audit_item_label': pl.Utf8,
        'organisation_id': pl.Utf8,
        'completed_at': pl.Utf8,
        'action_label': pl.Utf8,
        'deleted': pl.Utf8,
        'asset_id': pl.Utf8,
    },
    "action_timeline_items": {
        'item_id': pl.Utf8,
        'task_id': pl.Utf8,
        'organisation_id': pl.Utf8,
        'task_creator_id': pl.Utf8,
        'task_creator_name': pl.Utf8,
        'timestamp': pl.Utf8,
        'creator_id': pl.Utf8,
        'creator_name': pl.Utf8,
        'item_type': pl.Utf8,
        'item_data': pl.Utf8,
    },
    "action_assignees": {
        'id': pl.Utf8,
        'action_id': pl.Utf8,
        'assignee_id': pl.Utf8,
        'type': pl.Utf8,
        'name': pl.Utf8,
        'organisation_id': pl.Utf8,
        'modified_at': pl.Utf8,
        'exported_at': pl.Utf8,
    },
    "inspection_items": {
        'id': pl.Utf8,
        'item_id': pl.Utf8,
        'audit_id': pl.Utf8,
        'item_index': pl.Int32,
        'template_id': pl.Utf8,
        'parent_id': pl.Utf8,
        'created_at': pl.Utf8,
        'modified_at': pl.Utf8,
        'exported_at': pl.Utf8,
        'type': pl.Utf8,
        'category': pl.Utf8,
        'category_id': pl.Utf8,
        'organisation_id': pl.Utf8,
        'parent_ids': pl.Utf8,
        'label': pl.Utf8,
        'response': pl.Utf8,
        'response_id': pl.Utf8,
        'response_set_id': pl.Utf8,
        'is_failed_response': pl.Utf8,
        'comment': pl.Utf8,
        'media_files': pl.Utf8,
        'media_ids': pl.Utf8,
        'media_hypertext_reference': pl.Utf8,
        'score': pl.Float64,
        'max_score': pl.Int32,
        'score_percentage': pl.Float64,
        'combined_score': pl.Float64,
        'combined_max_score': pl.Int32,
        'combined_score_percentage': pl.Float64,
        'mandatory': pl.Utf8,
        'inactive': pl.Utf8,
        'location_latitude': pl.Utf8,
        'location_longitude': pl.Utf8,
    },
    "site_members": {
        'site_id': pl.Utf8,
        'member_id': pl.Utf8,
        'exported_at': pl.Utf8,
    }
}