CREATE OR REPLACE TABLE DEV_RAW_DB.IAUDITOR_RAW.IAUDITOR_GROUPS_FLTN AS
SELECT
    TO_CHAR(TO_TIMESTAMP_TZ(DATA_DATE), 'YYYY-MM-DD HH24:MI:SS') AS EXPORTED_AT,
    RECORD_INSERTED_AT,
    DATA.value:id::string AS GROUP_ID,
    DATA.value:organisation_id::string AS ORGANISATION_ID,
    DATA.value:name::string AS GROUP_NAME
FROM
    DEV_RAW_DB.IAUDITOR_RAW.IAUDITOR_GROUPS,
    LATERAL FLATTEN(input => JSON_PAYLOAD:data) AS DATA;
