CREATE OR REPLACE TABLE DEV_RAW_DB.IAUDITOR_RAW.IAUDITOR_GROUP_USERS_FLTN AS
SELECT
    TO_CHAR(TO_TIMESTAMP_TZ(DATA_DATE), 'YYYY-MM-DD HH24:MI:SS') AS EXPORTED_AT,
    DATA.value:user_id::string AS USER_ID,
    DATA.value:group_id::string AS GROUP_ID,
    DATA.value:organisation_id::string AS ORGANISATION_ID
FROM
    DEV_RAW_DB.IAUDITOR_RAW.IAUDITOR_GROUP_USERS,
    LATERAL FLATTEN(input => JSON_PAYLOAD:data) AS DATA;
