CREATE OR REPLACE TABLE DEV_RAW_DB.IAUDITOR_RAW.IAUDITOR_GROUPS_FLTN AS
SELECT
    DATA.value:id::string AS GROUP_ID,
    DATA.value:organisation_id::string AS ORGANISATION_ID,
    DATA.value:name::string AS NAME,
    TO_CHAR(TO_TIMESTAMP_TZ(DATA_DATE), 'YYYY-MM-DD') AS EXPORTED_AT

FROM
    DEV_RAW_DB.IAUDITOR_RAW.IAUDITOR_GROUPS,
    LATERAL FLATTEN(input => JSON_PAYLOAD:data) AS DATA;
