CREATE OR REPLACE TABLE DEV_RAW_DB.IAUDITOR_RAW.IAUDITOR_INSPECTIONS_FLTN AS
SELECT
    DATA_DATE,
    RECORD_INSERTED_AT,
    DATA.value:id::string AS AUDIT_ID,
    DATA.value:name::string AS NAME,
    DATA.value:archived::boolean AS ARCHIVED,
    DATA.value:organisation_id::string AS ORGANISATION_ID,
    DATA.value:owner_name::string AS OWNER_NAME,
    DATA.value:owner_id::string AS OWNER_ID,
    DATA.value:author_name::string AS AUTHOR_NAME,
    DATA.value:author_id::string AS AUTHOR_ID,
    DATA.value:score::int AS SCORE,
    DATA.value:max_score::int AS MAX_SCORE,
    DATA.value:score_percentage::float AS SCORE_PERCENTAGE,
    DATA.value:duration::int AS DURATION,
    DATA.value:site_id::string AS SITE_ID,
    DATA.value:template_name::string AS TEMPLATE_NAME,
    DATA.value:template_author::string AS TEMPLATE_AUTHOR,
    DATA.value:date_started::string AS DATE_STARTED,
    DATA.value:date_completed::string AS DATE_COMPLETED,
    DATA.value:date_modified::string AS DATE_MODIFIED,
    DATA.value:created_at::string AS CREATED_AT,
    DATA.value:modified_at::string AS MODIFIED_AT,
    DATA.value:latitude::float AS LATITUDE,
    DATA.value:longitude::float AS LONGITUDE,
    DATA.value:document_no::string AS DOCUMENT_NO,
    DATA.value:prepared_by::string AS PREPARED_BY,
    DATA.value:location::string AS LOCATION,
    DATA.value:conducted_on::string AS CONDUCTED_ON,
    DATA.value:personnel::string AS PERSONNEL,
    DATA.value:client_site::string AS CLIENT_SITE,
    DATA.value:asset_id::string AS ASSET_ID,
    DATA.value:web_report_link::string AS WEB_REPORT_LINK
FROM
    DEV_RAW_DB.IAUDITOR_RAW.IAUDITOR_INSPECTIONS,
    LATERAL FLATTEN(input => JSON_PAYLOAD:data) AS DATA;
