CREATE OR REPLACE TABLE DEV_RAW_DB.IAUDITOR_RAW.IAUDITOR_SCHEDULE_ASSIGNEES_FLTN AS
SELECT
    DATA_DATE,
    RECORD_INSERTED_AT,
    DATA.value:id::string AS SCHEDULE_ASSIGNEE_ID,
    DATA.value:schedule_id::string AS SCHEDULE_ID,
    DATA.value:assignee_id::string AS ASSIGNEE_ID,
    DATA.value:type::string AS ASSIGNEE_TYPE,
    DATA.value:name::string AS ASSIGNEE_NAME,
    DATA.value:organisation_id::string AS ORGANISATION_ID
FROM
    DEV_RAW_DB.IAUDITOR_RAW.IAUDITOR_SCHEDULE_ASSIGNEES,
    LATERAL FLATTEN(input => JSON_PAYLOAD:data) AS DATA;
