CREATE OR REPLACE TABLE DEV_RAW_DB.IAUDITOR_RAW.IAUDITOR_SITE_MEMBERS_FLTN AS
SELECT
    TO_CHAR(TO_TIMESTAMP_TZ(DATA_DATE), 'YYYY-MM-DD HH24:MI:SS') AS EXPORTED_AT,
    RECORD_INSERTED_AT,
    DATA.value:site_id::string AS SITE_ID,
    DATA.value:member_id::string AS MEMBER_ID
FROM
    DEV_RAW_DB.IAUDITOR_RAW.IAUDITOR_SITE_MEMBERS,
    LATERAL FLATTEN(input => JSON_PAYLOAD:data) AS DATA;
