CREATE OR REPLACE TABLE DEV_RAW_DB.IAUDITOR_RAW.IAUDITOR_SITE_MEMBERS_FLTN AS
SELECT
    DATA_DATE,
    RECORD_INSERTED_AT,
    DATA.value:site_id::string AS SITE_ID,
    DATA.value:member_id::string AS MEMBER_ID
FROM
    DEV_RAW_DB.IAUDITOR_RAW.IAUDITOR_SITE_MEMBERS,
    LATERAL FLATTEN(input => JSON_PAYLOAD:data) AS DATA;
